name: PHP Unit Tests

on:
    push:
    pull_request:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Set up PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.2'
                    extensions: mbstring, intl
                    coverage: xdebug

            -   name: Install dependencies
                run: cd examples/php && composer install --prefer-dist --no-progress

            -   name: Run tests
                run: cd examples/php && vendor/bin/phpunit tests
